[tool.poetry]
name = "json-generator"
version = "0.1.0"
description = ""
authors = ["vayaka <korotivan2005@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
reflex = "^0.2.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
